services:
  worldland:
    image: infonetlab/worldland_bcai
    container_name: worldland-bcai
    ports:
      - "8546:8545"
      - "30303:30303"
    stdin_open: true
    tty: true
    command:
      - --http
      - --http.addr
      - 0.0.0.0
      - --http.port
      - "8545"
      - --http.api
      - eth,net,web3,personal
      - console
